### ISSUE TITLE
Autogen kutuphanesini kurup calistirmak

### ISSUE THREAD

**Issue by bunyaminergen** [Shuhari-Researchers/AIDrivenUbuntuSecurityPatch#3]
Autogen kutuphanesini kurup calistirmak

**Comment by b-tekinli** [comment]
#### Ubuntu Kurulumu
1. Sanal ortam oluşturmak için: `sudo python3 venv myenv`
2. Sanal ortamı etkinleştirmek için: `source myenv/bin/activate`
3. Autogen kütüphanesini yüklemek için: `pip install autogen`
4. Sanal ortamda python kodu yazmak için: `vim shuhari_autogen.py`
5. Autogen modülündeki fonksiyonlarının çalıştığını görmek için:
    ```py
    import autogen
    print(dir(autogen))
    ```
